title: Learning
author: solayunus
email: solayunus@github.com
description: > # this means to ignore newlines until "baseurl:"
 Learning how to learn and relearn

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
