title: Learning
author: solayunus
email: solayunus19@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This website guide you on how to be a better learner.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
